export const TOGGLE_FILTER_BTN = 'TOGGLE_FILTER_BTN';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAIL = 'DATA_FAIL';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_COUNTERPART = 'ADD_COUNTERPART';

export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_THEME = 'SET_THEME';

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
