import React from 'react';

export const languages = {
  ru: {
    name: "ru",
    loading_text: "Загрузка...",
    header_text: "Транзакции и Фильтры. Часть 3",
    night_text: "Ночь",
    link_add_text: "Добавить новую транзакцию",
    there_is_not_transactions_text: "Транзакций, подходящих под выбранные фильтры — нет!",
    table_id_text: "Ай-ди",
    table_value_text: "Сумма",
    table_date_text: "Дата",
    table_counterpart_text: "Контрагент",
    table_name_text: "Имя",
    btn_income_text: "Доход",
    btn_expense_text: "Расход",
    btn_more_1000_text: "Более 1000р",
    btn_for_last_month_text: "За последний месяц",
    sure_leave_page_text: "Вы уверены, что хотите покинуть эту страницу? Данные формы не сохранятся.",
    select_type_text: "Выберете тип",
    select_value_text: "Укажите сумму",
    select_date_text: "Выберете дату",
    select_counterpart_text: "Выберете контрагента",
    select_time_text: "Устрановите время",
    placeholder_value_text: "Сумма",
    add_transaction_text: "Добавить новую транзакцию",
    add_counterpart_text: "Добавить нового контерагента",
    name_text: "Имя",
    link_to_main_page_text: "Главная",
    notification_text: "Уведомление",
    modal_mess_part_1: "Транзакция",
    modal_mess_part_2: "добавлена!",
    modal_btn_close_text: "Хорошо!",
    other_theme_text: "Другая тема",
    sort_text: "Sort",
    dialog_title_add_transaction: "Добавить новую транзакцию",
    dialog_titile_add_counterpart: "Добавить нового контерагента",
    transactions_table_text: "Транзакции",
    counterparts_table_text: "Контерагенты"
  },
  en: {
    name: "en",
    loading_text: "Loading...",
    header_text: "Transations & Filters 3",
    night_text: "It's Night",
    link_add_text: "Add a new transaction",
    there_is_not_transactions_text: "There is not some transactions that suitable for the actived filters.",
    table_id_text: "Id",
    table_value_text: "Value",
    table_date_text: "Date",
    table_counterpart_text: "Counterpart",
    table_name_text: "Name",
    btn_income_text: "Income",
    btn_expense_text: "Expense",
    btn_more_1000_text: "More 17$",
    btn_for_last_month_text: "For last month",
    sure_leave_page_text: "Do your sure you want to leave the page? The data won't save.",
    select_type_text: "Select a type",
    select_value_text: "Type a value",
    select_date_text: "Select a date",
    select_time_text: "Select a time",
    select_counterpart_text: "Select a counterpart",
    placeholder_value_text: "Value",
    add_transaction_text: "Add the new transaction",
    add_counterpart_text: "Add the new counterpart",
    name_text: "Name",
    link_to_main_page_text: "Main page",
    notification_text: "Notification",
    modal_mess_part_1: "The transaction",
    modal_mess_part_2: "is added!",
    modal_btn_close_text: "Ok!",
    other_theme_text: "Other theme",
    sort_text: "Сортировать",
    dialog_title_add_transaction: "Add a new transaction",
    dialog_titile_add_counterpart: "Add a new counterpart",
    transactions_table_text: "Transactions",
    counterparts_table_text: "Counterparts"
  }
};

export const LanguageContext = React.createContext(languages.ru);
